module.exports = {
  ImportDefaultSpecifier: 'ImportDefaultSpecifier',
  ImportSpecifier: 'ImportSpecifier',
  CallExpression: 'CallExpression',
  JSXAttribute: 'JSXAttribute',
  VariableDeclaration: 'VariableDeclaration',
  VariableDeclarator: 'VariableDeclarator',
  JSXElement: 'JSXElement',
  JSXExpressionContainer: 'JSXExpressionContainer',
  ObjectExpression: 'ObjectExpression',
  ArrayExpression: 'ArrayExpression',
  ArrowFunctionExpression: 'ArrowFunctionExpression',
  Identifier: 'Identifier',
  Literal: 'Literal',
  JSXText: 'JSXText',
  ReturnStatement: 'ReturnStatement',
  Property: 'Property',
  LogicalExpression: 'LogicalExpression',
  ConditionalExpression: 'ConditionalExpression',
  TemplateLiteral: 'TemplateLiteral',
};
